substitutions:
  # names
  name: "aquapi_snapcam"
  friendly_name: "AquaPi SnapCam"
  # App Version - Updated: 6/2024
  app_version: "24.11.0"

packages:
  device_base_camera: !include common/device_base_camera.yaml
  aquapi: !include common/aquapi.yaml
  ota_https: !include common/ota_https.yaml
  # debug: !include common/debug.yaml
