substitutions:
  # Logger Level - Can use VERBOSE for more information in Logs
  logger: "DEBUG"
  # Import Config
  import_config: "false"

  # I2C pins
  sdaPin: "26"
  sclPin: "27"

  sorting_group_misc_weight: '97'
  sorting_group_diagnostic_weight: '98'
  sorting_group_config_weight: '99'

esphome:
  min_version: 2024.6.0
  name: "${name}"
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  name_add_mac_suffix: true
  comment: "AquaPiCam ESP32 - AquaPi SnapCam"
  project:
    name: TheRealFalseReality.aquapi_SnapCam
    version: "${app_version}"
  on_boot: 
    then:
      - light.turn_on: camera_led
      - delay: 500ms
      - light.turn_off: camera_led
      - delay: 500ms
      - light.turn_on: camera_led
      - delay: 500ms
      - light.turn_off: camera_led

esp32:
  board: esp32cam
  framework:
    type: arduino

dashboard_import:
  package_import_url: github://TheRealFalseReality/esp32_snapcam/aquapi_camera_config.yaml@main
  import_full_config: ${import_config}

# Enable logging
logger:
  level: "${logger}"

api:

ota:
  - platform: esphome

wifi: 
  ap:

captive_portal:

web_server:
  version: 3
  sorting_groups:
    - id: sorting_group_diagnostic
      name: "AquaPi SnapCam Diagnostic"
      sorting_weight: ${sorting_group_diagnostic_weight}
    - id: sorting_group_config
      name: "AquaPi SnapCam Configuration"
      sorting_weight: ${sorting_group_config_weight}
    - id: sorting_group_misc
      name: "Misc. Sensors"
      sorting_weight: ${sorting_group_misc_weight}
  
improv_serial:

light:
# Internal Red LED
  - platform: status_led
    id: internal_led
    pin: 33
    
  - platform: binary
    output: camera_pin
    name: Camera LED
    id: camera_led
    icon: mdi:led-off

esp32_camera:
  name: AquaPi SnapCam
  external_clock:
    pin: 
      number: GPIO0
      ignore_strapping_warning: true
    frequency: 20MHz
  i2c_pins:
    sda: ${sdaPin}
    scl: ${sclPin}
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  # resolution: 1024X768
  # resolution: 720x1280
  # resolution: 1080x1920
  # resolution: 2560x1920
  # jpeg_quality: 10
  # vertical_flip: false
  # horizontal_mirror: False

# esp32_camera_web_server:
#   - port: 8080
#     mode: stream
#   - port: 8081
#     mode: snapshot

# LED Control
output:
  - platform: gpio
    pin: 4
    id: camera_pin

sensor:
  # Internal Temp.
  - platform: internal_temperature
    name: "Internal Temperature"
    icon: mdi:thermometer
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # Wifi Signal 
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    disabled_by_default: true
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    icon: mdi:wifi
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # Wifi %
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    icon: mdi:wifi
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # Uptime sensor
  - platform: uptime
    name: Uptime 

binary_sensor:
  # API Status
  - platform: status
    name: "Status"
    icon: mdi:check-circle
    web_server:
      sorting_group_id: sorting_group_diagnostic

text_sensor: 
  # Hostname
  - platform: template
    name: "Hostname"
    id: hostname
    icon: mdi:cellphone-arrow-down
    lambda: |-
      return {"${name}"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # Wifi Info
  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network
      web_server:
        sorting_group_id: sorting_group_diagnostic
    ssid:
      name: Connected SSID
      icon: mdi:wifi-arrow-left-right
      web_server:
        sorting_group_id: sorting_group_diagnostic

button:
  # Soft Restart
  - platform: restart
    id: restart_button
    name: "Restart"
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # Factory Reset
  - platform: factory_reset
    name: Factory Reset (USE WITH CAUTION)
    disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # Safe Mode Restart
  - platform: safe_mode
    name: "Restart in Safe Mode"
    id: restart_safe
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # Shutdown
  - platform: shutdown
    name: "Shutdown"
    disabled_by_default: true
    id: shutdown_button
    web_server:
      sorting_group_id: sorting_group_diagnostic